spring:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  profiles:
    include: oauth
  session:
    store-type: jdbc
  # Test OAuth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: test
            client-scope: profile,email
