spring:
  security:
    oauth2:
      client:
        registration:
          #google oauth2 setting
          google:
            client-id: 246885650695-m3t70kh268dr9o7idmlq7rrsu562nkoe.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          #naver oauth2 setting
          #redirect-uri 에러가 떴는데, 해당 uri를 문자열로 감싸줘야한다
          naver:
            client-id: expPluHpyjX7aOMd8rHr
            client-secret: Qaq1McxomZ
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
          #naver provider
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response


















